force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Cabo Verde</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Cameroon</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Is_main__c.field-meta.xml
<CustomField>
    <fullName>Is_main__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is a main address ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>zip/PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/street__c.field-meta.xml
<CustomField>
    <fullName>street__c</fullName>
    <label>street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MainAddressHandlerTest.cls
@isTest
public class MainAddressHandlerTest {

    /**
     * description:  test (if a new main address is inserted, then let it become the new account address)
     */
    @isTest
    static void toggleTraverseMainAddressToAccountOnInsertTest(){

        account testAccount =  new account(name='test');
        insert testAccount;
        Account_Address__c testBillingAddress=new Account_Address__c(
            name = 'test',
            city__c= 'test', 
            country__c= 'test', 
            state__c= 'test',
            street__c= 'test',
            PostalCode__c= 'test',
            Address_Type__c= 'Billing',
            Account__c = testAccount.id,
            Is_main__c=true
        );

        Account_Address__c testShippingAddress =  new Account_Address__c(
            name = 'test',
            city__c= 'test', 
            country__c= 'test', 
            state__c= 'test',
            street__c= 'test',
            PostalCode__c= 'test',
            Account__c = testAccount.id,
            Address_Type__c= 'Shipping',
            Is_main__c=true
        );

        insert new List<Account_Address__c>{
            testShippingAddress,
            testBillingAddress
        };


        list<account> testAccountList = [SELECT BillingCountry, ShippingCountry FROM Account WHERE id=:testAccount.id];

        System.assertEquals(1, testAccountList.size());
        System.assertEquals(testShippingAddress.country__c,testAccountList[0].ShippingCountry);
        System.assertEquals(testBillingAddress.country__c,testAccountList[0].BillingCountry);
    }
    /**
     * description:  test (if  main address is updated, then update account address)
     */


    @isTest
    static void toggleMainAddressOnUpdateTest(){

        account testAccount =  new account(name='test');
        insert testAccount;

        list<Account_Address__c> testAccountAddresses = new List<Account_Address__c>();

        Account_Address__c testOldBillingAddress=new Account_Address__c(
            name = 'initial main',
            city__c= 'test', 
            country__c= 'test', 
            state__c= 'test',
            street__c= 'test',
            PostalCode__c= 'test',
            Address_Type__c= 'Billing',
            Account__c = testAccount.id,
            Is_main__c=true
        );

        Account_Address__c testOldShippingAddress =  new Account_Address__c(
            name = 'initial main',
            city__c= 'test', 
            country__c= 'test', 
            state__c= 'test',
            street__c= 'test',
            PostalCode__c= 'test',
            Account__c = testAccount.id,
            Address_Type__c= 'Shipping',
            Is_main__c=true
        );
        Account_Address__c newtestBillingAddress = new Account_Address__c(
            name = 'new or final main',
            city__c= 'test', 
            country__c= 'new test', 
            state__c= 'test',
            street__c= 'test',
            PostalCode__c= 'test',
            Address_Type__c= 'Billing',
            Account__c = testAccount.id,
            Is_main__c=false
        );
        Account_Address__c newtestShippingAddress = new Account_Address__c(
            name = 'new or final main',
            city__c= 'test', 
            country__c= 'new test', 
            state__c= 'test',
            street__c= 'test',
            PostalCode__c= 'test',
            Account__c = testAccount.id,
            Address_Type__c= 'Shipping',
            Is_main__c=false
        );

        insert new List<Account_Address__c>{ newtestBillingAddress, testOldShippingAddress, testOldBillingAddress, newtestShippingAddress };

        list<account> testAccountList = [SELECT BillingCountry, ShippingCountry FROM Account WHERE id=:testAccount.id limit 1]; 

        System.assert(testOldShippingAddress.is_main__c);
        System.assert(testOldBillingAddress.is_main__c);
        System.assert(newtestShippingAddress.is_main__c == false);
        System.assert(newtestBillingAddress.is_main__c == false);
        System.assertEquals(testOldShippingAddress.country__c,testAccountList[0].ShippingCountry);
        System.assertEquals(testOldBillingAddress.country__c,testAccountList[0].BillingCountry);

        newtestBillingAddress.Is_main__c = true;
        newtestShippingAddress.Is_main__c = true;
        update new List<Account_Address__c>{newtestBillingAddress,newtestShippingAddress};

        testAccountList = [SELECT BillingCountry, ShippingCountry FROM Account WHERE id=:testAccount.id limit 1];
        
        System.assert(([SELECT id, is_main__c from Account_Address__c where id =:testOldShippingAddress.id limit 1])[0].is_main__c ==false);
        System.assert(([SELECT id, is_main__c from Account_Address__c where id =:testOldBillingAddress.id limit 1])[0].is_main__c ==false);
        System.assert(newtestShippingAddress.is_main__c );
        System.assert(newtestBillingAddress.is_main__c );

        System.assertEquals(newtestShippingAddress.country__c,testAccountList[0].ShippingCountry);
        System.assertEquals(newtestBillingAddress.country__c,testAccountList[0].BillingCountry);

    }

    @istest 
    static void updateAccountMainAddressOnMainAddressUpdateTest(){
        account testAccount =  new account(name='test');
        insert testAccount;
        Account_Address__c testBillingAddress=new Account_Address__c(
            name = 'test',
            city__c= 'test', 
            country__c= 'test', 
            state__c= 'test',
            street__c= 'test',
            PostalCode__c= 'test',
            Address_Type__c= 'Billing',
            Account__c = testAccount.id,
            Is_main__c=true
        );

        Account_Address__c testShippingAddress =  new Account_Address__c(
            name = 'test',
            city__c= 'test', 
            country__c= 'test', 
            state__c= 'test',
            street__c= 'test',
            PostalCode__c= 'test',
            Account__c = testAccount.id,
            Address_Type__c= 'Shipping',
            Is_main__c=true
        );

        insert new List<Account_Address__c>{
            testShippingAddress,
            testBillingAddress
        };


        list<account> testAccountList = [SELECT BillingCountry, ShippingCountry FROM Account WHERE id=:testAccount.id];

        System.assertEquals(1, testAccountList.size());
        System.assertEquals(testShippingAddress.country__c,testAccountList[0].ShippingCountry);
        System.assertEquals(testBillingAddress.country__c,testAccountList[0].BillingCountry);


        testShippingAddress.country__c= 'Cameroon';
        testBillingAddress.country__c= 'Cameroon';

        update new List<Account_Address__c>{
            testShippingAddress,
            testBillingAddress
        };

        testAccountList = [SELECT BillingCountry, ShippingCountry FROM Account WHERE id=:testAccount.id];
        
        System.assertEquals(1, testAccountList.size());
        System.assertEquals(testShippingAddress.country__c,testAccountList[0].ShippingCountry);
        System.assertEquals(testBillingAddress.country__c,testAccountList[0].BillingCountry);

    }

}