force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Cabo Verde</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Cameroon</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Is_main__c.field-meta.xml
<CustomField>
    <fullName>Is_main__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is a main address ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>zip/PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/street__c.field-meta.xml
<CustomField>
    <fullName>street__c</fullName>
    <label>street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountAddressControllerTest.cls
@isTest
public with sharing class AccountAddressControllerTest {
    
    @TestSetup
    static void createAddressesForAccount(){
        account acc = new Account(name='Test');
        insert acc;
        List<Account_Address__c> relatedAccountAddress =  new List<Account_Address__c>();
        for (Integer i = 0; i < 200; i++) {
            relatedAccountAddress.add(
                new Account_Address__c( 
                    name = acc.name,
                    city__c = 'test city' + i,
                    Country__c = 'test country' + i,
                    state__c = 'test state'+i,
                    Is_main__c= false,
                    street__c = 'test city' + i,
                    PostalCode__c = 'test postal code'+ i,
                    Address_Type__c = 'Billing',
                    Account__c = acc.id)
            );
        }
        insert relatedAccountAddress;
    }

    @isTest 
    static void getRelatedAddressesTest(){
        list<account> acc = [SELECT id,name from account LIMIT 1];
        List<Account_Address__c> relatedAddresses = AccountAddressController.getRelatedAddresses(String.valueOf(acc[0].id));
        System.assertEquals(200, relatedAddresses.size());
    }

    @isTest 
    static void deleteAddressTest(){
        list<account> acc = [SELECT id,name from account LIMIT 1];
        list<Account_Address__c> accAddress = [SELECT id,name from Account_Address__c WHERE Account__c  =:acc[0].id LIMIT 1];
        id accAddressID = accAddress[0].id;
        AccountAddressController.deleteAddress(String.valueOf(accAddressID));
        list<Account_Address__c> deletedAccAddress = [SELECT id,name from Account_Address__c WHERE id  =:accAddressID];
        System.assertEquals(0, deletedAccAddress.size());
    }
}