force-app/main/default/objects/Account_Address__c/Account_Address__c.object-meta.xml
<CustomObject>
    <label>Account Address</label>
    <nameField>
        <label>Account Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Address__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Addresses</relationshipLabel>
    <relationshipName>Account_Addresses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Burkina Faso</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Cabo Verde</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Cameroon</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/Is_main__c.field-meta.xml
<CustomField>
    <fullName>Is_main__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is a main address ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>zip/PostalCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Address__c/fields/street__c.field-meta.xml
<CustomField>
    <fullName>street__c</fullName>
    <label>street</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddressMassUpdateQueue.cls
/**
 * Author: Ngum buka Fon Nyuydze
 * Created-on: 02/01/2023 
 * last-edited on: 01/01/2023
 * Description: perform async update of the main addresses that don't match the parent account adresses, less than 250,000 records. 
 */

public without sharing class AddressMassUpdateQueue implements Queueable {

    public void execute(QueueableContext context) {
        List<Account_Address__c> mainAddressList = [SELECT country__c, state__c, PostalCode__c,Address_Type__c FROM Account_Address__c WHERE is_main__c=true];
 
        list<id> relatedAccountIds = new list<id>();
 
        for(Account_Address__c address : mainAddressList){
             relatedAccountIds.add(address.Account__c);
        }
 
        List<account> relatedAccounts = [SELECT id,BillingCity,BillingCountry,BillingState, BillingStreet, BillingPostalCode, name,ShippingCity, ShippingCountry, ShippingState, ShippingStreet, ShippingPostalCode FROM Account WHERE id in :relatedAccountIds];
     
        List<Account_Address__c> addressesToUpdate = new List<Account_Address__c>();
        
        for(Account_Address__c address : mainAddressList){
         for(Account acc:relatedAccounts){
     
             if(address.Account__c ==acc.id && address.Address_Type__c=='Shipping' ){
                if(!(address.city__c == acc.ShippingCity && address.country__c == acc.ShippingCountry && address.state__c == acc.ShippingState && address.street__c == acc.ShippingStreet && address.PostalCode__c == acc.ShippingPostalCode && address.name == acc.name)){
                         
                         address.city__c = acc.ShippingCity ;
                         address.country__c=  acc.ShippingCountry;
                         address.state__c = acc.ShippingState;
                         address.street__c=acc.ShippingStreet;
                         address.PostalCode__c = acc.ShippingPostalCode;
                         address.name = acc.name;
                         addressesToUpdate.add(address);
                }
             }
             
             if(address.Account__c ==acc.id && address.Address_Type__c=='Billing' ){
                    if(!(address.city__c == acc.BillingCity &&
                        address.country__c == acc.BillingCountry &&
                        address.state__c == acc.BillingState &&
                        address.street__c == acc.BillingStreet &&
                        address.PostalCode__c == acc.BillingPostalCode &&
                        address.name == acc.name)){
    
                            address.city__c = acc.BillingCity ;
                            address.country__c=  acc.BillingCountry;
                            address.state__c = acc.BillingState;
                            address.street__c=acc.BillingStreet;
                            address.PostalCode__c = acc.BillingPostalCode;
                            address.name = acc.name;
                            addressesToUpdate.add(address);
                    }
                }
             }
         }
 
         update addressesToUpdate;
    }
}